
url: 'https://johanna-hedges.github.io/' 
baseurl: 'atest/'

back_to_top: true back_to_top_text: "Back to top"

footer_content: 'Copyright © 2025 Minimal Example.'

last_edit_timestamp: true last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub" gh_edit_repository: "https://github.com/yourusername/your-repo-name/"
gh_edit_branch: "main" gh_edit_source: "/docs" gh_edit_view_mode: "tree"
