remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

title: Minimal Just-the-Docs Site

url: 'https://johanna-hedges.github.io/'
baseurl: '/testing/'


gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/johanna-hedges/testing/"
gh_edit_branch: "main"
gh_edit_source: "/docs"
gh_edit_view_mode: "tree"





