remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

title: Minimal Just-the-Docs Site

url: 'https://johanna-hedges.github.io/'
baseurl: '/testing/'

back_to_top: true
back_to_top_text: "Back to top"

footer_content: |
  <script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "YOUR_PROJECT_ID");
  </script>


last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/johanna-hedges/testing/"
gh_edit_branch: "main"
gh_edit_source: "/docs"
gh_edit_view_mode: "tree"



