
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

include:
  - _includes/custom_head.html

title: Minimal Just-the-Docs Site

url: 'https://johanna-hedges.github.io/'
baseurl: '/testing/'

back_to_top: true
back_to_top_text: "Back to top"


